name: super_camera
description: A camera plugin for Flutter.
version: 0.0.1
author: Maruice Parrish <bparr2450@gmail.com>
homepage: https://github.com/bparrishMines/super/tree/master/super_camera

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_info: ^0.4.1+1
  uuid: ^2.0.1
  flutter_plugin_android_lifecycle: ^1.0.3
  penguin_plugin:
    git:
      url: git://github.com/bparrishMines/penguin.git
      path: penguin_plugin
      ref: reference_counting
  penguin:
    git:
      url: git://github.com/bparrishMines/penguin.git
      path: penguin
      ref: reference_counting

dev_dependencies:
  flutter_test:
    sdk: flutter
  permission_handler: ^3.2.2
  build_runner: ^1.6.7
  penguin_generator:
    git:
      url: git://github.com/bparrishMines/penguin.git
      path: penguin_generator
      ref: reference_counting

flutter:
  plugin:
    androidPackage: super_plugins.super_camera
    pluginClass: SuperCameraPlugin
