name: super_camera
description: A camera plugin for Flutter.
version: 0.0.1
author: Maruice Parrish <bparr2450@gmail.com>
homepage: https://github.com/bparrishMines/super/tree/master/super_camera

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  uuid: 2.0.1
  penguin:
    path: ../../penguin/penguin2/todo_reporter.dart/penguin
  flutter:
    sdk: flutter

dev_dependencies:
  permission_handler: ^3.2.2
  build_runner: ^1.6.7
  penguin_generator:
    path: ../../penguin/penguin2/todo_reporter.dart/penguin_generator
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: super_plugins.super_camera
    pluginClass: SuperCameraPlugin
