name: super_camera
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  device_info: ^0.4.2+4
  reference: ^0.1.2+1
  plugin_platform_interface: ^1.0.2
  flutter_plugin_android_lifecycle: ^1.0.8
  permission_handler: ^5.0.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: bparrishmines.superplugins.super_camera
        pluginClass: SuperCameraPlugin
      ios:
        pluginClass: SuperCameraPlugin
