name: super_camera_example
description: Demonstrates how to use the super_camera plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^3.2.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  super_camera:
    path: ../

flutter:
  uses-material-design: true
